c_stop_go_features = ["tfsstabwdp_" + str(i) for i in range(149, 297)]
i_stop_go_features = ["tfsstabwdp_" + str(i) for i in range(297, 444 + 1)]

c_stop_go_features_res = ["tfsstabwdp_" + str(i) + "_prime" for i in range(149, 297)]
i_stop_go_features_res = ["tfsstabwdp_" + str(i) + "_prime" for i in range(297, 444 + 1)]

BASELINE = "baseline_year_1_arm_1"
FOLLOWUP = "2_year_follow_up_y_arm_1"
TARGET = "demo_sex_v2"

mri_features_res = ['smri_thick_cdk_banksstslh_prime',
 'smri_thick_cdk_cdacatelh_prime',
 'smri_thick_cdk_cdmdfrlh_prime',
 'smri_thick_cdk_cuneuslh_prime',
 'smri_thick_cdk_ehinallh_prime',
 'smri_thick_cdk_fusiformlh_prime',
 'smri_thick_cdk_ifpllh_prime',
 'smri_thick_cdk_iftmlh_prime',
 'smri_thick_cdk_ihcatelh_prime',
 'smri_thick_cdk_locclh_prime',
 'smri_thick_cdk_lobfrlh_prime',
 'smri_thick_cdk_linguallh_prime',
 'smri_thick_cdk_mobfrlh_prime',
 'smri_thick_cdk_mdtmlh_prime',
 'smri_thick_cdk_parahpallh_prime',
 'smri_thick_cdk_paracnlh_prime',
 'smri_thick_cdk_parsopclh_prime',
 'smri_thick_cdk_parsobislh_prime',
 'smri_thick_cdk_parstgrislh_prime',
 'smri_thick_cdk_pericclh_prime',
 'smri_thick_cdk_postcnlh_prime',
 'smri_thick_cdk_ptcatelh_prime',
 'smri_thick_cdk_precnlh_prime',
 'smri_thick_cdk_pclh_prime',
 'smri_thick_cdk_rracatelh_prime',
 'smri_thick_cdk_rrmdfrlh_prime',
 'smri_thick_cdk_sufrlh_prime',
 'smri_thick_cdk_supllh_prime',
 'smri_thick_cdk_sutmlh_prime',
 'smri_thick_cdk_smlh_prime',
 'smri_thick_cdk_frpolelh_prime',
 'smri_thick_cdk_tmpolelh_prime',
 'smri_thick_cdk_trvtmlh_prime',
 'smri_thick_cdk_insulalh_prime',
 'smri_thick_cdk_banksstsrh_prime',
 'smri_thick_cdk_cdacaterh_prime',
 'smri_thick_cdk_cdmdfrrh_prime',
 'smri_thick_cdk_cuneusrh_prime',
 'smri_thick_cdk_ehinalrh_prime',
 'smri_thick_cdk_fusiformrh_prime',
 'smri_thick_cdk_ifplrh_prime',
 'smri_thick_cdk_iftmrh_prime',
 'smri_thick_cdk_ihcaterh_prime',
 'smri_thick_cdk_loccrh_prime',
 'smri_thick_cdk_lobfrrh_prime',
 'smri_thick_cdk_lingualrh_prime',
 'smri_thick_cdk_mobfrrh_prime',
 'smri_thick_cdk_mdtmrh_prime',
 'smri_thick_cdk_parahpalrh_prime',
 'smri_thick_cdk_paracnrh_prime',
 'smri_thick_cdk_parsopcrh_prime',
 'smri_thick_cdk_parsobisrh_prime',
 'smri_thick_cdk_parstgrisrh_prime',
 'smri_thick_cdk_periccrh_prime',
 'smri_thick_cdk_postcnrh_prime',
 'smri_thick_cdk_ptcaterh_prime',
 'smri_thick_cdk_precnrh_prime',
 'smri_thick_cdk_pcrh_prime',
 'smri_thick_cdk_rracaterh_prime',
 'smri_thick_cdk_rrmdfrrh_prime',
 'smri_thick_cdk_sufrrh_prime',
 'smri_thick_cdk_suplrh_prime',
 'smri_thick_cdk_sutmrh_prime',
 'smri_thick_cdk_smrh_prime',
 'smri_thick_cdk_frpolerh_prime',
 'smri_thick_cdk_tmpolerh_prime',
 'smri_thick_cdk_trvtmrh_prime',
 'smri_thick_cdk_insularh_prime',
 'smri_thick_cdk_meanlh_prime',
 'smri_thick_cdk_meanrh_prime',
 'smri_thick_cdk_mean_prime']